In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('IMDB-Movie-Data.csv')

In [3]:
#display top 10 rows of the dataset

In [4]:
df.head(10)

,Rank,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
0,1,Guardians of the Galaxy,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0
1,2,Prometheus,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0
2,3,Split,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62.0
3,4,Sing,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59.0
4,5,Suicide Squad,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,325.02,40.0
5,6,The Great Wall,"Action,Adventure,Fantasy",European mercenaries searching for black powde...,Yimou Zhang,"Matt Damon, Tian Jing, Willem Dafoe, Andy Lau",2016,103,6.1,56036,45.13,42.0
6,7,La La Land,"Comedy,Drama,Music",A jazz pianist falls for an aspiring actress i...,Damien Chazelle,"Ryan Gosling, Emma Stone, Rosemarie DeWitt, J....",2016,128,8.3,258682,151.06,93.0
7,8,Mindhorn,Comedy,A has-been actor best known for playing the ti...,Sean Foley,"Essie Davis, Andrea Riseborough, Julian Barrat...",2016,89,6.4,2490,NaN,71.0
8,9,The Lost City of Z,"Action,Adventure,Biography","A true-life drama, centering on British explor...",James Gray,"Charlie Hunnam, Robert Pattinson, Sienna Mille...",2016,141,7.1,7188,8.01,78.0
9,10,Passengers,"Adventure,Drama,Romance",A spacecraft traveling to a distant colony pla...,Morten Tyldum,"Jennifer Lawrence, Chris Pratt, Michael Sheen,...",2016,116,7.0,192177,100.01,41.0

In [5]:
#check the null values on the dataset

In [9]:
df.isnull().sum()

Rank                    0
Title                   0
Genre                   0
Description             0
Director                0
Actors                  0
Year                    0
Runtime (Minutes)       0
Rating                  0
Votes                   0
Revenue (Millions)    128
Metascore              64
dtype: int64

In [12]:
df=df.dropna()

In [13]:
df.isnull().sum()

Rank                  0
Title                 0
Genre                 0
Description           0
Director              0
Actors                0
Year                  0
Runtime (Minutes)     0
Rating                0
Votes                 0
Revenue (Millions)    0
Metascore             0
dtype: int64

In [14]:
#check the overall statistics of the dataset

In [15]:
df.describe()

,Rank,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
count,838.000000,838.00000,838.000000,838.000000,8.380000e+02,838.000000,838.000000
mean,485.247017,2012.50716,114.638425,6.814320,1.932303e+05,84.564558,59.575179
std,286.572065,3.17236,18.470922,0.877754,1.930990e+05,104.520227,16.952416
min,1.000000,2006.00000,66.000000,1.900000,1.780000e+02,0.000000,11.000000
25%,238.250000,2010.00000,101.000000,6.300000,6.127650e+04,13.967500,47.000000
50%,475.500000,2013.00000,112.000000,6.900000,1.368795e+05,48.150000,60.000000
75%,729.750000,2015.00000,124.000000,7.500000,2.710830e+05,116.800000,72.000000
max,1000.000000,2016.00000,187.000000,9.000000,1.791916e+06,936.630000,100.000000

In [16]:
df.head()

,Rank,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
0,1,Guardians of the Galaxy,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0
1,2,Prometheus,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0
2,3,Split,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62.0
3,4,Sing,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59.0
4,5,Suicide Squad,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,325.02,40.0

In [25]:
df[df['Runtime (Minutes)']>=180]['Title']

82     The Wolf of Wall Street
88           The Hateful Eight
311             La vie d'Adèle
Name: Title, dtype: object

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 838 entries, 0 to 999
Data columns (total 12 columns):
Rank                  838 non-null int64
Title                 838 non-null object
Genre                 838 non-null object
Description           838 non-null object
Director              838 non-null object
Actors                838 non-null object
Year                  838 non-null int64
Runtime (Minutes)     838 non-null int64
Rating                838 non-null float64
Votes                 838 non-null int64
Revenue (Millions)    838 non-null float64
Metascore             838 non-null float64
dtypes: float64(3), int64(4), object(5)
memory usage: 85.1+ KB

In [26]:
#in which year there was the highest average voting

In [27]:
df.head()

,Rank,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
0,1,Guardians of the Galaxy,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0
1,2,Prometheus,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0
2,3,Split,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62.0
3,4,Sing,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59.0
4,5,Suicide Squad,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,325.02,40.0

In [32]:
df.groupby('Year')['Votes'].mean().sort_values(ascending=False).head(3)

Year
2012    290861.483871
2006    277232.219512
2009    267180.577778
Name: Votes, dtype: float64

In [33]:
#in which year there was the highest average revenue

In [34]:
df.head()

,Rank,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
0,1,Guardians of the Galaxy,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0
1,2,Prometheus,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0
2,3,Split,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62.0
3,4,Sing,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59.0
4,5,Suicide Squad,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,325.02,40.0

In [40]:
df.groupby('Year')['Runtime (Minutes)'].mean().sort_values(ascending=False).head(3)

Year
2007    122.000000
2006    119.170732
2012    118.467742
Name: Runtime (Minutes), dtype: float64

In [37]:
df.columns

Index(['Rank', 'Title', 'Genre', 'Description', 'Director', 'Actors', 'Year',
       'Runtime (Minutes)', 'Rating', 'Votes', 'Revenue (Millions)',
       'Metascore'],
      dtype='object')

In [41]:
#find the average rating of each director

In [42]:
df.head()

,Rank,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
0,1,Guardians of the Galaxy,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0
1,2,Prometheus,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0
2,3,Split,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62.0
3,4,Sing,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59.0
4,5,Suicide Squad,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,325.02,40.0

In [44]:
df.groupby('Director')['Rating'].mean().sort_values(ascending=False)

Director
Christopher Nolan                   8.68
Olivier Nakache                     8.60
Makoto Shinkai                      8.60
Aamir Khan                          8.50
Florian Henckel von Donnersmarck    8.50
                                    ...
Sam Taylor-Johnson                  4.10
Joey Curtis                         4.00
George Nolfi                        3.90
James Wong                          2.70
Jason Friedberg                     1.90
Name: Rating, Length: 524, dtype: float64

In [45]:
#display top 10 lengthy movies title and runtime

In [46]:
df.head()

,Rank,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
0,1,Guardians of the Galaxy,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0
1,2,Prometheus,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0
2,3,Split,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62.0
3,4,Sing,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59.0
4,5,Suicide Squad,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,325.02,40.0

In [55]:
df[['Title','Runtime (Minutes)']].sort_values(by='Runtime (Minutes)',ascending=False).head(10)

                                        Title  Runtime (Minutes)
88                          The Hateful Eight                187
82                    The Wolf of Wall Street                180
311                            La vie d'Adèle                180
267                               Cloud Atlas                172
430                                  3 Idiots                170
75   Pirates of the Caribbean: At World's End                169
36                               Interstellar                169
271         The Hobbit: An Unexpected Journey                169
425       The Curious Case of Benjamin Button                166
126           Transformers: Age of Extinction                165

In [48]:
df.columns

Index(['Rank', 'Title', 'Genre', 'Description', 'Director', 'Actors', 'Year',
       'Runtime (Minutes)', 'Rating', 'Votes', 'Revenue (Millions)',
       'Metascore'],
      dtype='object')

In [56]:
#display number of movies per year

In [57]:
df.head()

,Rank,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
0,1,Guardians of the Galaxy,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0
1,2,Prometheus,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0
2,3,Split,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62.0
3,4,Sing,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59.0
4,5,Suicide Squad,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,325.02,40.0

In [60]:
df['Year'].value_counts()

2016    198
2015    109
2014     93
2013     84
2012     62
2011     57
2010     57
2008     48
2009     45
2007     44
2006     41
Name: Year, dtype: int64

In [61]:
#find the highest revenue movie title

In [62]:
df.head()

,Rank,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
0,1,Guardians of the Galaxy,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0
1,2,Prometheus,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0
2,3,Split,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62.0
3,4,Sing,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59.0
4,5,Suicide Squad,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,325.02,40.0

In [66]:
df[df['Runtime (Minutes)']==df[ 'Runtime (Minutes)'].max()]['Title']

88    The Hateful Eight
Name: Title, dtype: object

In [67]:
#display top 10 highest rated movie titles and directors

In [68]:
df.head()

,Rank,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
0,1,Guardians of the Galaxy,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0
1,2,Prometheus,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0
2,3,Split,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62.0
3,4,Sing,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59.0
4,5,Suicide Squad,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,325.02,40.0

In [71]:
df[['Title','Director','Rating']].sort_values(by='Rating',ascending=False).head(10)

                     Title                          Director  Rating
54         The Dark Knight                 Christopher Nolan     9.0
80               Inception                 Christopher Nolan     8.8
36            Interstellar                 Christopher Nolan     8.6
249       The Intouchables                   Olivier Nakache     8.6
96           Kimi no na wa                    Makoto Shinkai     8.6
124  The Dark Knight Rises                 Christopher Nolan     8.5
991       Taare Zameen Par                        Aamir Khan     8.5
133               Whiplash                   Damien Chazelle     8.5
99            The Departed                   Martin Scorsese     8.5
476    The Lives of Others  Florian Henckel von Donnersmarck     8.5

In [72]:
#display top 10 highest revenue movie titles

In [73]:
df.head()

,Rank,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
0,1,Guardians of the Galaxy,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0
1,2,Prometheus,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0
2,3,Split,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62.0
3,4,Sing,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59.0
4,5,Suicide Squad,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,325.02,40.0

In [76]:
df[['Title','Revenue (Millions)']].sort_values(by='Revenue (Millions)',ascending=False).head(10)

                                          Title  Revenue (Millions)
50   Star Wars: Episode VII - The Force Awakens              936.63
87                                       Avatar              760.51
85                               Jurassic World              652.18
76                                 The Avengers              623.28
54                              The Dark Knight              533.32
12                                    Rogue One              532.17
119                                Finding Dory              486.29
94                      Avengers: Age of Ultron              458.99
124                       The Dark Knight Rises              448.13
578             The Hunger Games: Catching Fire              424.65

In [75]:
df.columns

Index(['Rank', 'Title', 'Genre', 'Description', 'Director', 'Actors', 'Year',
       'Runtime (Minutes)', 'Rating', 'Votes', 'Revenue (Millions)',
       'Metascore'],
      dtype='object')

In [78]:
df.nlargest(10,'Revenue (Millions)')['Title']

50     Star Wars: Episode VII - The Force Awakens
87                                         Avatar
85                                 Jurassic World
76                                   The Avengers
54                                The Dark Knight
12                                      Rogue One
119                                  Finding Dory
94                        Avengers: Age of Ultron
124                         The Dark Knight Rises
578               The Hunger Games: Catching Fire
Name: Title, dtype: object

In [79]:
#find the average rating of movies year wise

In [80]:
df.head()

,Rank,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
0,1,Guardians of the Galaxy,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0
1,2,Prometheus,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0
2,3,Split,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62.0
3,4,Sing,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59.0
4,5,Suicide Squad,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,325.02,40.0

In [81]:
df.groupby('Year')['Rating'].mean()

Year
2006    7.143902
2007    7.140909
2008    6.708333
2009    6.911111
2010    6.894737
2011    6.945614
2012    6.933871
2013    6.832143
2014    6.822581
2015    6.674312
2016    6.644444
Name: Rating, dtype: float64

In [83]:
#classify movies based on ratings[excellent,good and average]

In [84]:
df.head()

,Rank,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
0,1,Guardians of the Galaxy,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0
1,2,Prometheus,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0
2,3,Split,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62.0
3,4,Sing,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59.0
4,5,Suicide Squad,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,325.02,40.0

In [85]:
def rating(x):
    if x>8:
        return 'Excellent'
    elif x>6:
        return 'Good'
    else:
        return 'Average'
df['Quality']=df['Rating'].apply(rating)

C:\Users\Dell\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [87]:
df.head(20)

,Rank,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore,Quality
0,1,Guardians of the Galaxy,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0,Excellent
1,2,Prometheus,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0,Good
2,3,Split,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62.0,Good
3,4,Sing,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59.0,Good
4,5,Suicide Squad,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,325.02,40.0,Good
5,6,The Great Wall,"Action,Adventure,Fantasy",European mercenaries searching for black powde...,Yimou Zhang,"Matt Damon, Tian Jing, Willem Dafoe, Andy Lau",2016,103,6.1,56036,45.13,42.0,Good
6,7,La La Land,"Comedy,Drama,Music",A jazz pianist falls for an aspiring actress i...,Damien Chazelle,"Ryan Gosling, Emma Stone, Rosemarie DeWitt, J....",2016,128,8.3,258682,151.06,93.0,Excellent
8,9,The Lost City of Z,"Action,Adventure,Biography","A true-life drama, centering on British explor...",James Gray,"Charlie Hunnam, Robert Pattinson, Sienna Mille...",2016,141,7.1,7188,8.01,78.0,Good
9,10,Passengers,"Adventure,Drama,Romance",A spacecraft traveling to a distant colony pla...,Morten Tyldum,"Jennifer Lawrence, Chris Pratt, Michael Sheen,...",2016,116,7.0,192177,100.01,41.0,Good
10,11,Fantastic Beasts and Where to Find Them,"Adventure,Family,Fantasy",The adventures of writer Newt Scamander in New...,David Yates,"Eddie Redmayne, Katherine Waterston, Alison Su...",2016,133,7.5,232072,234.02,66.0,Good
11,12,Hidden Figures,"Biography,Drama,History",The story of a team of female African-American...,Theodore Melfi,"Taraji P. Henson, Octavia Spencer, Janelle Mon...",2016,127,7.8,93103,169.27,74.0,Good
12,13,Rogue One,"Action,Adventure,Sci-Fi",The Rebel Alliance makes a risky move to steal...,Gareth Edwards,"Felicity Jones, Diego Luna, Alan Tudyk, Donnie...",2016,133,7.9,323118,532.17,65.0,Good
13,14,Moana,"Animation,Adventure,Comedy","In Ancient Polynesia, when a terrible curse in...",Ron Clements,"Auli'i Cravalho, Dwayne Johnson, Rachel House,...",2016,107,7.7,118151,248.75,81.0,Good
14,15,Colossal,"Action,Comedy,Drama",Gloria is an out-of-work party girl forced to ...,Nacho Vigalondo,"Anne Hathaway, Jason Sudeikis, Austin Stowell,...",2016,109,6.4,8612,2.87,70.0,Good
15,16,The Secret Life of Pets,"Animation,Adventure,Comedy",The quiet life of a terrier named Max is upend...,Chris Renaud,"Louis C.K., Eric Stonestreet, Kevin Hart, Lake...",2016,87,6.6,120259,368.31,61.0,Good
16,17,Hacksaw Ridge,"Biography,Drama,History","WWII American Army Medic Desmond T. Doss, who ...",Mel Gibson,"Andrew Garfield, Sam Worthington, Luke Bracey,...",2016,139,8.2,211760,67.12,71.0,Excellent
17,18,Jason Bourne,"Action,Thriller",The CIA's most dangerous former operative is d...,Paul Greengrass,"Matt Damon, Tommy Lee Jones, Alicia Vikander,V...",2016,123,6.7,150823,162.16,58.0,Good
18,19,Lion,"Biography,Drama",A five-year-old Indian boy gets lost on the st...,Garth Davis,"Dev Patel, Nicole Kidman, Rooney Mara, Sunny P...",2016,118,8.1,102061,51.69,69.0,Excellent
19,20,Arrival,"Drama,Mystery,Sci-Fi",When twelve mysterious spacecraft appear aroun...,Denis Villeneuve,"Amy Adams, Jeremy Renner, Forest Whitaker,Mich...",2016,116,8.0,340798,100.50,81.0,Good
20,21,Gold,"Adventure,Drama,Thriller","Kenny Wells, a prospector desperate for a luck...",Stephen Gaghan,"Matthew McConaughey, Edgar Ramírez, Bryce Dall...",2016,120,6.7,19053,7.22,49.0,Good

In [88]:
#count number of action movies

In [89]:
df.head()

,Rank,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore,Quality
0,1,Guardians of the Galaxy,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0,Excellent
1,2,Prometheus,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0,Good
2,3,Split,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62.0,Good
3,4,Sing,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59.0,Good
4,5,Suicide Squad,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,325.02,40.0,Good

In [90]:
df['Genre'].value_counts()

Action,Adventure,Sci-Fi       50
Comedy,Drama,Romance          30
Drama                         29
Drama,Romance                 27
Animation,Adventure,Comedy    26
                              ..
Horror,Mystery,Sci-Fi          1
Comedy,Drama,Fantasy           1
Comedy,Drama,Musical           1
Animation,Drama,Fantasy        1
Comedy,Horror,Sci-Fi           1
Name: Genre, Length: 189, dtype: int64

In [94]:
len(df[df['Genre'].str.contains('Action',case=False)])

277

In [95]:
#find the unique values from genera

In [96]:
my_list=[]
for x in df['Genre']:
    my_list.append(x.split(','))
print(my_list)

[['Action', 'Adventure', 'Sci-Fi'], ['Adventure', 'Mystery', 'Sci-Fi'], ['Horror', 'Thriller'], ['Animation', 'Comedy', 'Family'], ['Action', 'Adventure', 'Fantasy'], ['Action', 'Adventure', 'Fantasy'], ['Comedy', 'Drama', 'Music'], ['Action', 'Adventure', 'Biography'], ['Adventure', 'Drama', 'Romance'], ['Adventure', 'Family', 'Fantasy'], ['Biography', 'Drama', 'History'], ['Action', 'Adventure', 'Sci-Fi'], ['Animation', 'Adventure', 'Comedy'], ['Action', 'Comedy', 'Drama'], ['Animation', 'Adventure', 'Comedy'], ['Biography', 'Drama', 'History'], ['Action', 'Thriller'], ['Biography', 'Drama'], ['Drama', 'Mystery', 'Sci-Fi'], ['Adventure', 'Drama', 'Thriller'], ['Drama'], ['Animation', 'Adventure', 'Comedy'], ['Action', 'Adventure', 'Sci-Fi'], ['Comedy'], ['Action', 'Adventure', 'Drama'], ['Comedy'], ['Drama', 'Thriller'], ['Action', 'Adventure', 'Sci-Fi'], ['Action', 'Adventure', 'Comedy'], ['Action', 'Horror', 'Sci-Fi'], ['Action', 'Adventure', 'Sci-Fi'], ['Adventure', 'Drama', 'Sci-Fi'], ['Action', 'Adventure', 'Fantasy'], ['Action', 'Adventure', 'Western'], ['Animation', 'Adventure', 'Comedy'], ['Drama'], ['Biography', 'Drama', 'History'], ['Drama'], ['Action', 'Adventure', 'Fantasy'], ['Drama', 'Thriller'], ['Action', 'Adventure', 'Sci-Fi'], ['Action', 'Adventure', 'Fantasy'], ['Action', 'Adventure', 'Fantasy'], ['Comedy', 'Drama'], ['Action', 'Crime', 'Thriller'], ['Action', 'Crime', 'Drama'], ['Adventure', 'Drama', 'History'], ['Crime', 'Horror', 'Thriller'], ['Drama', 'Romance'], ['Comedy', 'Drama', 'Romance'], ['Biography', 'Drama'], ['Action', 'Adventure', 'Sci-Fi'], ['Crime', 'Drama', 'Mystery'], ['Drama', 'Romance', 'Thriller'], ['Drama', 'Mystery', 'Sci-Fi'], ['Action', 'Adventure', 'Comedy'], ['Drama', 'History', 'Thriller'], ['Action', 'Adventure', 'Sci-Fi'], ['Drama'], ['Action', 'Drama', 'Thriller'], ['Action', 'Drama', 'Romance'], ['Drama', 'Fantasy'], ['Drama', 'Romance'], ['Animation', 'Adventure', 'Comedy'], ['Action', 'Adventure', 'Fantasy'], ['Action', 'Sci-Fi'], ['Adventure', 'Drama', 'War'], ['Action', 'Adventure', 'Fantasy'], ['Action', 'Comedy', 'Fantasy'], ['Action', 'Adventure', 'Sci-Fi'], ['Comedy', 'Drama'], ['Biography', 'Comedy', 'Crime'], ['Crime', 'Drama', 'Mystery'], ['Action', 'Crime', 'Thriller'], ['Action', 'Adventure', 'Sci-Fi'], ['Crime', 'Drama'], ['Action', 'Adventure', 'Fantasy'], ['Crime', 'Drama', 'Mystery'], ['Action', 'Crime', 'Drama'], ['Crime', 'Drama', 'Mystery'], ['Action', 'Adventure', 'Fantasy'], ['Drama'], ['Comedy', 'Crime', 'Drama'], ['Action', 'Adventure', 'Sci-Fi'], ['Action', 'Comedy', 'Crime'], ['Animation', 'Drama', 'Fantasy'], ['Horror', 'Mystery', 'Sci-Fi'], ['Drama', 'Mystery', 'Thriller'], ['Crime', 'Drama', 'Thriller'], ['Biography', 'Crime', 'Drama'], ['Action', 'Adventure', 'Fantasy'], ['Adventure', 'Drama', 'Sci-Fi'], ['Action', 'Adventure', 'Comedy'], ['Crime', 'Drama', 'Thriller'], ['Comedy'], ['Action', 'Adventure', 'Drama'], ['Drama', 'Mystery', 'Sci-Fi'], ['Action', 'Horror', 'Thriller'], ['Biography', 'Drama', 'History'], ['Action', 'Fantasy', 'War'], ['Adventure', 'Drama', 'Fantasy'], ['Comedy'], ['Horror', 'Thriller'], ['Drama', 'Horror', 'Mystery'], ['Animation', 'Adventure', 'Comedy'], ['Adventure', 'Drama', 'Family'], ['Adventure', 'Mystery', 'Sci-Fi'], ['Adventure', 'Comedy', 'Romance'], ['Action', 'Thriller'], ['Adventure', 'Drama', 'Family'], ['Action', 'Adventure', 'Sci-Fi'], ['Adventure', 'Crime', 'Mystery'], ['Comedy', 'Family', 'Musical'], ['Adventure', 'Drama', 'Thriller'], ['Drama'], ['Adventure', 'Comedy', 'Drama'], ['Drama', 'Horror', 'Thriller'], ['Drama', 'Music'], ['Action', 'Crime', 'Thriller'], ['Crime', 'Drama', 'Thriller'], ['Crime', 'Drama', 'Thriller'], ['Drama', 'Romance'], ['Mystery', 'Thriller'], ['Action', 'Adventure', 'Sci-Fi'], ['Comedy', 'Family'], ['Biography', 'Comedy', 'Drama'], ['Drama'], ['Drama', 'Western'], ['Drama', 'Mystery', 'Romance'], ['Comedy', 'Drama'], ['Action', 'Drama', 'Mystery'], ['Comedy'], ['Action', 'Adventure', 'Crime'], ['Adventure', 'Family', 'Fantasy'], ['Adventure', 'Sci-Fi', 'Thriller'], ['Drama'], ['Action', 'Crime', 'Drama'], ['Action', 'Horror', 'Sci-Fi'], ['Action', 'Adventure', 'Sci-Fi'], ['Comedy', 'Drama', 'Romance'], ['Action', 'Comedy', 'Fantasy'], ['Action', 'Comedy', 'Mystery'], ['Action', 'Comedy', 'Crime'], ['Action', 'Adventure', 'Sci-Fi'], ['Action', 'Adventure', 'Crime'], ['Action', 'Adventure', 'Thriller'], ['Drama', 'Fantasy', 'Romance'], ['Action', 'Adventure', 'Comedy'], ['Biography', 'Drama', 'History'], ['Action', 'Drama', 'History'], ['Action', 'Adventure', 'Thriller'], ['Crime', 'Drama', 'Thriller'], ['Animation', 'Adventure', 'Family'], ['Drama', 'Romance', 'Sci-Fi'], ['Animation', 'Adventure', 'Comedy'], ['Action', 'Adventure', 'Family'], ['Action', 'Adventure', 'Drama'], ['Action', 'Comedy'], ['Horror', 'Mystery', 'Thriller'], ['Action', 'Adventure', 'Comedy'], ['Comedy', 'Romance'], ['Horror', 'Mystery'], ['Drama', 'Family', 'Fantasy'], ['Drama', 'Thriller'], ['Drama', 'War'], ['Drama', 'Fantasy', 'Horror'], ['Crime', 'Drama'], ['Comedy', 'Drama', 'Romance'], ['Drama', 'Romance'], ['Crime', 'Drama', 'History'], ['Horror', 'Sci-Fi', 'Thriller'], ['Action', 'Drama', 'Sport'], ['Action', 'Adventure', 'Sci-Fi'], ['Adventure', 'Biography', 'Drama'], ['Biography', 'Drama', 'Thriller'], ['Action', 'Comedy', 'Crime'], ['Action', 'Adventure', 'Sci-Fi'], ['Drama', 'Fantasy', 'Horror'], ['Biography', 'Drama', 'Thriller'], ['Action', 'Adventure', 'Sci-Fi'], ['Action', 'Adventure', 'Mystery'], ['Action', 'Adventure', 'Sci-Fi'], ['Drama', 'Horror'], ['Comedy', 'Drama', 'Romance'], ['Comedy', 'Romance'], ['Action', 'Adventure', 'Drama'], ['Drama'], ['Action', 'Adventure', 'Sci-Fi'], ['Action', 'Adventure', 'Fantasy'], ['Action', 'Adventure', 'Fantasy'], ['Action', 'Adventure', 'Sci-Fi'], ['Action', 'Adventure', 'Comedy'], ['Action', 'Comedy'], ['Action', 'Adventure', 'Sci-Fi'], ['Animation', 'Adventure', 'Comedy'], ['Horror', 'Mystery'], ['Crime', 'Drama', 'Mystery'], ['Comedy', 'Crime'], ['Drama'], ['Comedy', 'Drama', 'Romance'], ['Action', 'Adventure', 'Sci-Fi'], ['Action', 'Adventure', 'Family'], ['Drama', 'Fantasy', 'War'], ['Crime', 'Drama', 'Thriller'], ['Action', 'Adventure', 'Drama'], ['Action', 'Adventure', 'Thriller'], ['Action', 'Adventure', 'Drama'], ['Drama', 'Romance'], ['Biography', 'Drama', 'History'], ['Drama', 'Horror', 'Thriller'], ['Adventure', 'Comedy', 'Drama'], ['Action', 'Adventure', 'Romance'], ['Action', 'Drama', 'War'], ['Animation', 'Adventure', 'Comedy'], ['Animation', 'Adventure', 'Comedy'], ['Action', 'Adventure', 'Sci-Fi'], ['Adventure', 'Family', 'Fantasy'], ['Drama', 'Musical', 'Romance'], ['Drama', 'Sci-Fi', 'Thriller'], ['Comedy', 'Drama'], ['Action', 'Comedy', 'Crime'], ['Biography', 'Comedy', 'Drama'], ['Comedy', 'Drama', 'Romance'], ['Drama', 'Thriller'], ['Biography', 'Drama', 'History'], ['Action', 'Adventure', 'Sci-Fi'], ['Horror', 'Mystery', 'Thriller'], ['Comedy'], ['Action', 'Adventure', 'Sci-Fi'], ['Action', 'Drama', 'Sci-Fi'], ['Horror'], ['Drama', 'Thriller'], ['Comedy', 'Drama', 'Romance'], ['Drama', 'Thriller'], ['Comedy', 'Drama'], ['Drama'], ['Action', 'Adventure', 'Comedy'], ['Drama', 'Horror', 'Thriller'], ['Comedy'], ['Drama', 'Sci-Fi'], ['Action', 'Adventure', 'Sci-Fi'], ['Action', 'Adventure', 'Thriller'], ['Adventure', 'Fantasy'], ['Action', 'Comedy', 'Crime'], ['Comedy', 'Drama', 'Music'], ['Action', 'Adventure', 'Mystery'], ['Action', 'Comedy', 'Crime'], ['Crime', 'Drama', 'History'], ['Comedy'], ['Action', 'Adventure', 'Sci-Fi'], ['Crime', 'Mystery', 'Thriller'], ['Action', 'Adventure', 'Crime'], ['Biography', 'Drama', 'Romance'], ['Action', 'Adventure'], ['Action', 'Fantasy'], ['Action', 'Comedy'], ['Action', 'Adventure', 'Sci-Fi'], ['Action', 'Comedy', 'Crime'], ['Action', 'Drama', 'Horror'], ['Comedy', 'Music', 'Romance'], ['Comedy'], ['Action', 'Adventure', 'Fantasy'], ['Drama', 'Romance'], ['Animation', 'Adventure', 'Comedy'], ['Comedy', 'Drama'], ['Biography', 'Crime', 'Drama'], ['Drama', 'History'], ['Action', 'Crime', 'Thriller'], ['Action', 'Biography', 'Drama'], ['Horror'], ['Comedy', 'Romance'], ['Comedy', 'Romance'], ['Comedy', 'Crime', 'Drama'], ['Adventure', 'Family', 'Fantasy'], ['Action', 'Crime', 'Thriller'], ['Comedy', 'Romance'], ['Biography', 'Drama', 'Sport'], ['Drama', 'Romance'], ['Drama', 'Horror'], ['Adventure', 'Fantasy'], ['Adventure', 'Family', 'Fantasy'], ['Action', 'Drama', 'Sci-Fi'], ['Action', 'Adventure', 'Sci-Fi'], ['Comedy', 'Horror', 'Thriller'], ['Action', 'Crime', 'Thriller'], ['Crime', 'Drama', 'Music'], ['Drama'], ['Action', 'Crime', 'Thriller'], ['Action', 'Sci-Fi', 'Thriller'], ['Biography', 'Drama'], ['Action', 'Adventure', 'Fantasy'], ['Drama', 'Horror', 'Sci-Fi'], ['Biography', 'Comedy', 'Drama'], ['Crime', 'Horror', 'Thriller'], ['Crime', 'Drama', 'Mystery'], ['Animation', 'Adventure', 'Comedy'], ['Action', 'Biography', 'Drama'], ['Biography', 'Drama'], ['Biography', 'Drama', 'History'], ['Action', 'Biography', 'Drama'], ['Comedy', 'Drama', 'Romance'], ['Drama', 'Romance'], ['Comedy', 'Romance'], ['Action', 'Crime', 'Thriller'], ['Action', 'Crime', 'Drama'], ['Action', 'Drama', 'Thriller'], ['Adventure', 'Family', 'Fantasy'], ['Action', 'Adventure'], ['Action', 'Adventure', 'Romance'], ['Adventure', 'Family', 'Fantasy'], ['Crime', 'Drama'], ['Comedy', 'Horror'], ['Comedy', 'Fantasy', 'Romance'], ['Drama'], ['Comedy', 'Drama'], ['Comedy', 'Drama', 'Romance'], ['Adventure', 'Sci-Fi', 'Thriller'], ['Action', 'Adventure', 'Fantasy'], ['Biography', 'Drama', 'Romance'], ['Comedy', 'Fantasy'], ['Comedy', 'Drama', 'Fantasy'], ['Comedy'], ['Horror', 'Thriller'], ['Action', 'Adventure', 'Sci-Fi'], ['Adventure', 'Comedy', 'Horror'], ['Comedy', 'Mystery'], ['Drama'], ['Adventure', 'Drama', 'Fantasy'], ['Action', 'Adventure'], ['Action', 'Adventure', 'Drama'], ['Action', 'Drama', 'Sci-Fi'], ['Action', 'Mystery', 'Sci-Fi'], ['Action', 'Crime', 'Drama'], ['Action', 'Crime', 'Fantasy'], ['Biography', 'Comedy', 'Drama'], ['Action', 'Crime', 'Thriller'], ['Biography', 'Crime', 'Drama'], ['Drama', 'Sport'], ['Adventure', 'Comedy', 'Drama'], ['Action', 'Adventure', 'Thriller'], ['Comedy', 'Fantasy', 'Horror'], ['Drama', 'Sport'], ['Drama', 'History', 'Thriller'], ['Animation', 'Action', 'Adventure'], ['Action', 'Adventure', 'Drama'], ['Action', 'Comedy', 'Family'], ['Action', 'Adventure', 'Drama'], ['Action', 'Adventure', 'Sci-Fi'], ['Action', 'Adventure', 'Sci-Fi'], ['Action', 'Comedy'], ['Action', 'Crime', 'Drama'], ['Biography', 'Drama'], ['Comedy'], ['Drama', 'Fantasy', 'Romance'], ['Action', 'Adventure', 'Sci-Fi'], ['Comedy'], ['Comedy', 'Drama'], ['Animation', 'Action', 'Adventure'], ['Animation', 'Adventure', 'Comedy'], ['Drama', 'Romance'], ['Drama', 'Mystery', 'Thriller'], ['Drama', 'History', 'Thriller'], ['Animation', 'Adventure', 'Comedy'], ['Action', 'Adventure', 'Sci-Fi'], ['Adventure', 'Comedy'], ['Action', 'Thriller'], ['Comedy', 'Music'], ['Animation', 'Adventure', 'Comedy'], ['Action', 'Adventure', 'Crime'], ['Comedy', 'Drama', 'Horror'], ['Adventure', 'Family', 'Fantasy'], ['Drama'], ['Action', 'Drama', 'Thriller'], ['Drama'], ['Action', 'Horror', 'Romance'], ['Action', 'Drama', 'Fantasy'], ['Action', 'Crime', 'Drama'], ['Drama', 'Fantasy', 'Romance'], ['Action', 'Crime', 'Thriller'], ['Action', 'Mystery', 'Thriller'], ['Comedy', 'Drama'], ['Comedy'], ['Action', 'Adventure', 'Horror'], ['Action', 'Adventure', 'Thriller'], ['Drama', 'Romance'], ['Drama', 'Thriller'], ['Action', 'Comedy', 'Crime'], ['Adventure', 'Family', 'Fantasy'], ['Drama', 'Romance'], ['Animation', 'Family', 'Fantasy'], ['Drama', 'Romance'], ['Action', 'Sci-Fi'], ['Adventure', 'Comedy', 'Drama'], ['Animation', 'Action', 'Adventure'], ['Drama', 'Horror'], ['Action', 'Adventure', 'Sci-Fi'], ['Comedy', 'Drama'], ['Action', 'Horror', 'Mystery'], ['Action', 'Thriller'], ['Action', 'Adventure', 'Sci-Fi'], ['Drama'], ['Comedy', 'Drama', 'Romance'], ['Comedy', 'Crime'], ['Comedy', 'Romance'], ['Drama', 'Romance'], ['Crime', 'Drama', 'Thriller'], ['Horror', 'Mystery', 'Thriller'], ['Biography', 'Drama'], ['Adventure', 'Comedy', 'Family'], ['Action', 'Adventure', 'Crime'], ['Action', 'Crime', 'Mystery'], ['Mystery', 'Thriller'], ['Action', 'Sci-Fi', 'Thriller'], ['Action', 'Comedy', 'Crime'], ['Biography', 'Crime', 'Drama'], ['Biography', 'Drama', 'History'], ['Action', 'Adventure', 'Sci-Fi'], ['Adventure', 'Family', 'Fantasy'], ['Biography', 'Drama', 'History'], ['Biography', 'Comedy', 'Drama'], ['Drama', 'Thriller'], ['Comedy', 'Drama', 'Romance'], ['Drama', 'Romance', 'Sci-Fi'], ['Action', 'Crime', 'Drama'], ['Adventure', 'Comedy', 'Drama'], ['Comedy', 'Drama', 'Family'], ['Drama', 'Romance', 'Thriller'], ['Comedy', 'Crime', 'Drama'], ['Animation', 'Comedy', 'Family'], ['Drama', 'Horror', 'Sci-Fi'], ['Action', 'Adventure', 'Drama'], ['Action', 'Horror', 'Sci-Fi'], ['Action', 'Crime', 'Sport'], ['Drama', 'Horror', 'Sci-Fi'], ['Drama', 'Horror', 'Sci-Fi'], ['Action', 'Adventure', 'Comedy'], ['Mystery', 'Sci-Fi', 'Thriller'], ['Crime', 'Drama', 'Thriller'], ['Animation', 'Adventure', 'Comedy'], ['Action', 'Sci-Fi', 'Thriller'], ['Drama', 'Romance'], ['Comedy', 'Drama', 'Music'], ['Crime', 'Drama', 'Thriller'], ['Comedy', 'Drama', 'Romance'], ['Comedy', 'Romance'], ['Drama', 'Sci-Fi', 'Thriller'], ['Drama', 'War'], ['Action', 'Crime', 'Drama'], ['Sci-Fi', 'Thriller'], ['Adventure', 'Drama', 'Horror'], ['Comedy', 'Drama', 'Romance'], ['Action', 'Adventure', 'Drama'], ['Action', 'Crime', 'Drama'], ['Adventure', 'Fantasy'], ['Drama', 'Romance'], ['Biography', 'History', 'Thriller'], ['Crime', 'Drama', 'Thriller'], ['Action', 'Drama', 'History'], ['Crime', 'Drama', 'Thriller'], ['Action', 'Biography', 'Drama'], ['Adventure', 'Horror'], ['Action', 'Adventure', 'Sci-Fi'], ['Action', 'Adventure', 'Mystery'], ['Comedy', 'Drama', 'Romance'], ['Horror', 'Thriller'], ['Action', 'Sci-Fi', 'Thriller'], ['Biography', 'Drama'], ['Action', 'Crime', 'Drama'], ['Action', 'Crime', 'Mystery'], ['Action', 'Adventure', 'Comedy'], ['Mystery', 'Thriller'], ['Mystery', 'Sci-Fi', 'Thriller'], ['Drama', 'Mystery', 'Sci-Fi'], ['Comedy', 'Drama'], ['Adventure', 'Family', 'Fantasy'], ['Biography', 'Drama', 'Sport'], ['Comedy', 'Drama', 'Romance'], ['Biography', 'Drama', 'Romance'], ['Action', 'Adventure', 'Sci-Fi'], ['Mystery', 'Thriller'], ['Mystery', 'Thriller'], ['Action', 'Drama', 'Fantasy'], ['Action', 'Adventure', 'Biography'], ['Adventure', 'Comedy', 'Sci-Fi'], ['Action', 'Adventure', 'Thriller'], ['Fantasy', 'Horror'], ['Horror', 'Mystery'], ['Animation', 'Adventure', 'Comedy'], ['Action', 'Adventure', 'Drama'], ['Adventure', 'Family', 'Fantasy'], ['Action', 'Adventure', 'Sci-Fi'], ['Comedy', 'Drama'], ['Comedy', 'Drama'], ['Crime', 'Drama', 'Thriller'], ['Comedy', 'Romance'], ['Animation', 'Comedy', 'Family'], ['Comedy', 'Drama'], ['Comedy', 'Drama'], ['Biography', 'Drama', 'Sport'], ['Action', 'Adventure', 'Fantasy'], ['Action', 'Drama', 'History'], ['Action', 'Adventure', 'Sci-Fi'], ['Action', 'Adventure', 'Mystery'], ['Crime', 'Drama', 'Mystery'], ['Action'], ['Comedy', 'Romance'], ['Comedy', 'Drama', 'Romance'], ['Biography', 'Drama', 'Sport'], ['Action', 'Fantasy', 'Thriller'], ['Biography', 'Drama', 'Sport'], ['Action', 'Drama', 'Fantasy'], ['Adventure', 'Sci-Fi', 'Thriller'], ['Animation', 'Adventure', 'Comedy'], ['Drama', 'Mystery', 'Thriller'], ['Drama', 'Romance'], ['Crime', 'Drama', 'Mystery'], ['Comedy', 'Romance', 'Sport'], ['Comedy', 'Family'], ['Drama', 'Horror', 'Mystery'], ['Action', 'Drama', 'Sport'], ['Action', 'Adventure', 'Comedy'], ['Drama', 'Mystery', 'Sci-Fi'], ['Animation', 'Action', 'Comedy'], ['Action', 'Crime', 'Drama'], ['Action', 'Crime', 'Drama'], ['Animation', 'Action', 'Adventure'], ['Crime', 'Drama'], ['Comedy', 'Crime'], ['Drama'], ['Action', 'Adventure', 'Fantasy'], ['Drama', 'Fantasy', 'Romance'], ['Comedy', 'Drama'], ['Drama', 'Fantasy', 'Thriller'], ['Biography', 'Crime', 'Drama'], ['Comedy', 'Drama', 'Romance'], ['Action', 'Crime', 'Drama'], ['Sci-Fi'], ['Action', 'Comedy', 'Romance'], ['Adventure', 'Comedy', 'Drama'], ['Comedy', 'Crime', 'Drama'], ['Action', 'Fantasy', 'Horror'], ['Drama', 'Horror'], ['Horror'], ['Action', 'Thriller'], ['Action', 'Adventure', 'Mystery'], ['Action', 'Adventure', 'Fantasy'], ['Adventure', 'Comedy', 'Family'], ['Comedy', 'Drama', 'Romance'], ['Comedy'], ['Comedy', 'Drama', 'Horror'], ['Comedy', 'Romance'], ['Mystery', 'Romance', 'Sci-Fi'], ['Crime', 'Drama'], ['Drama', 'Horror', 'Mystery'], ['Comedy'], ['Biography', 'Drama'], ['Comedy', 'Drama', 'Thriller'], ['Drama', 'History', 'War'], ['Comedy', 'Drama'], ['Action', 'Comedy', 'Fantasy'], ['Drama', 'Horror', 'Musical'], ['Horror', 'Mystery', 'Thriller'], ['Comedy', 'Music'], ['Biography', 'Crime', 'Drama'], ['Drama'], ['Action', 'Adventure', 'Comedy'], ['Crime', 'Drama', 'Mystery'], ['Drama'], ['Action', 'Comedy', 'Crime'], ['Comedy', 'Drama', 'Romance'], ['Crime', 'Drama', 'Mystery'], ['Action', 'Comedy', 'Crime'], ['Drama'], ['Drama', 'Romance'], ['Crime', 'Drama', 'Mystery'], ['Adventure', 'Comedy', 'Romance'], ['Comedy', 'Crime', 'Drama'], ['Adventure', 'Drama', 'Thriller'], ['Crime', 'Drama', 'Thriller'], ['Drama', 'History', 'Thriller'], ['Action', 'Adventure', 'Sci-Fi'], ['Horror'], ['Action', 'Crime', 'Mystery'], ['Comedy', 'Romance'], ['Comedy'], ['Action', 'Drama', 'Thriller'], ['Action', 'Adventure', 'Sci-Fi'], ['Drama', 'Mystery', 'Thriller'], ['Comedy', 'Drama', 'Romance'], ['Action', 'Fantasy', 'Horror'], ['Drama', 'Romance'], ['Biography', 'Drama'], ['Biography', 'Drama'], ['Action', 'Adventure', 'Sci-Fi'], ['Animation', 'Adventure', 'Comedy'], ['Drama', 'Mystery', 'Thriller'], ['Action', 'Horror', 'Sci-Fi'], ['Drama', 'Romance'], ['Action', 'Adventure', 'Drama'], ['Adventure', 'Drama', 'Fantasy'], ['Drama', 'Romance', 'Sci-Fi'], ['Action', 'Adventure', 'Thriller'], ['Comedy', 'Fantasy'], ['Action', 'Comedy', 'Crime'], ['Adventure', 'Drama', 'Romance'], ['Action', 'Crime', 'Drama'], ['Comedy', 'Drama', 'Romance'], ['Crime', 'Drama'], ['Crime', 'Drama', 'Mystery'], ['Action', 'Adventure', 'Sci-Fi'], ['Animation', 'Fantasy'], ['Animation', 'Adventure', 'Comedy'], ['Drama', 'Mystery', 'War'], ['Comedy', 'Romance'], ['Animation', 'Comedy', 'Family'], ['Comedy'], ['Horror', 'Mystery', 'Thriller'], ['Action', 'Adventure', 'Drama'], ['Comedy'], ['Drama'], ['Adventure', 'Biography', 'Drama'], ['Comedy'], ['Horror', 'Thriller'], ['Action', 'Drama', 'Family'], ['Comedy', 'Fantasy', 'Horror'], ['Comedy', 'Romance'], ['Drama', 'Mystery', 'Romance'], ['Action', 'Adventure', 'Comedy'], ['Thriller'], ['Comedy'], ['Adventure', 'Comedy', 'Sci-Fi'], ['Mystery', 'Thriller'], ['Comedy', 'Drama'], ['Adventure', 'Drama', 'Family'], ['Horror', 'Thriller'], ['Action', 'Drama', 'Romance'], ['Drama', 'Romance'], ['Action', 'Adventure', 'Fantasy'], ['Comedy'], ['Action', 'Biography', 'Drama'], ['Drama', 'Mystery', 'Romance'], ['Adventure', 'Drama', 'Western'], ['Drama', 'Music', 'Romance'], ['Comedy', 'Romance', 'Western'], ['Horror', 'Thriller'], ['Adventure', 'Family', 'Fantasy'], ['Crime', 'Drama', 'Mystery'], ['Horror', 'Mystery'], ['Comedy', 'Crime', 'Drama'], ['Action', 'Comedy', 'Romance'], ['Action', 'Biography', 'Drama'], ['Drama', 'Music'], ['Comedy', 'Drama'], ['Drama', 'Thriller', 'War'], ['Action', 'Mystery', 'Thriller'], ['Horror', 'Sci-Fi', 'Thriller'], ['Comedy', 'Drama', 'Romance'], ['Action', 'Adventure', 'Fantasy'], ['Drama', 'Mystery', 'Romance'], ['Drama'], ['Action', 'Adventure', 'Thriller'], ['Animation', 'Action', 'Adventure'], ['Drama', 'Fantasy', 'Mystery'], ['Drama', 'Sci-Fi'], ['Animation', 'Adventure', 'Comedy'], ['Horror', 'Thriller'], ['Action', 'Mystery', 'Thriller'], ['Action', 'Mystery', 'Sci-Fi'], ['Crime', 'Drama', 'Thriller'], ['Comedy', 'Drama', 'Romance'], ['Biography', 'Drama', 'Thriller'], ['Action', 'Adventure', 'Family'], ['Animation', 'Comedy', 'Family'], ['Action', 'Crime

In [97]:
new_list=[]
for x in my_list:
    for y in x:
        new_list.append(y.split(','))
print(new_list)

[['Action'], ['Adventure'], ['Sci-Fi'], ['Adventure'], ['Mystery'], ['Sci-Fi'], ['Horror'], ['Thriller'], ['Animation'], ['Comedy'], ['Family'], ['Action'], ['Adventure'], ['Fantasy'], ['Action'], ['Adventure'], ['Fantasy'], ['Comedy'], ['Drama'], ['Music'], ['Action'], ['Adventure'], ['Biography'], ['Adventure'], ['Drama'], ['Romance'], ['Adventure'], ['Family'], ['Fantasy'], ['Biography'], ['Drama'], ['History'], ['Action'], ['Adventure'], ['Sci-Fi'], ['Animation'], ['Adventure'], ['Comedy'], ['Action'], ['Comedy'], ['Drama'], ['Animation'], ['Adventure'], ['Comedy'], ['Biography'], ['Drama'], ['History'], ['Action'], ['Thriller'], ['Biography'], ['Drama'], ['Drama'], ['Mystery'], ['Sci-Fi'], ['Adventure'], ['Drama'], ['Thriller'], ['Drama'], ['Animation'], ['Adventure'], ['Comedy'], ['Action'], ['Adventure'], ['Sci-Fi'], ['Comedy'], ['Action'], ['Adventure'], ['Drama'], ['Comedy'], ['Drama'], ['Thriller'], ['Action'], ['Adventure'], ['Sci-Fi'], ['Action'], ['Adventure'], ['Comedy'], ['Action'], ['Horror'], ['Sci-Fi'], ['Action'], ['Adventure'], ['Sci-Fi'], ['Adventure'], ['Drama'], ['Sci-Fi'], ['Action'], ['Adventure'], ['Fantasy'], ['Action'], ['Adventure'], ['Western'], ['Animation'], ['Adventure'], ['Comedy'], ['Drama'], ['Biography'], ['Drama'], ['History'], ['Drama'], ['Action'], ['Adventure'], ['Fantasy'], ['Drama'], ['Thriller'], ['Action'], ['Adventure'], ['Sci-Fi'], ['Action'], ['Adventure'], ['Fantasy'], ['Action'], ['Adventure'], ['Fantasy'], ['Comedy'], ['Drama'], ['Action'], ['Crime'], ['Thriller'], ['Action'], ['Crime'], ['Drama'], ['Adventure'], ['Drama'], ['History'], ['Crime'], ['Horror'], ['Thriller'], ['Drama'], ['Romance'], ['Comedy'], ['Drama'], ['Romance'], ['Biography'], ['Drama'], ['Action'], ['Adventure'], ['Sci-Fi'], ['Crime'], ['Drama'], ['Mystery'], ['Drama'], ['Romance'], ['Thriller'], ['Drama'], ['Mystery'], ['Sci-Fi'], ['Action'], ['Adventure'], ['Comedy'], ['Drama'], ['History'], ['Thriller'], ['Action'], ['Adventure'], ['Sci-Fi'], ['Drama'], ['Action'], ['Drama'], ['Thriller'], ['Action'], ['Drama'], ['Romance'], ['Drama'], ['Fantasy'], ['Drama'], ['Romance'], ['Animation'], ['Adventure'], ['Comedy'], ['Action'], ['Adventure'], ['Fantasy'], ['Action'], ['Sci-Fi'], ['Adventure'], ['Drama'], ['War'], ['Action'], ['Adventure'], ['Fantasy'], ['Action'], ['Comedy'], ['Fantasy'], ['Action'], ['Adventure'], ['Sci-Fi'], ['Comedy'], ['Drama'], ['Biography'], ['Comedy'], ['Crime'], ['Crime'], ['Drama'], ['Mystery'], ['Action'], ['Crime'], ['Thriller'], ['Action'], ['Adventure'], ['Sci-Fi'], ['Crime'], ['Drama'], ['Action'], ['Adventure'], ['Fantasy'], ['Crime'], ['Drama'], ['Mystery'], ['Action'], ['Crime'], ['Drama'], ['Crime'], ['Drama'], ['Mystery'], ['Action'], ['Adventure'], ['Fantasy'], ['Drama'], ['Comedy'], ['Crime'], ['Drama'], ['Action'], ['Adventure'], ['Sci-Fi'], ['Action'], ['Comedy'], ['Crime'], ['Animation'], ['Drama'], ['Fantasy'], ['Horror'], ['Mystery'], ['Sci-Fi'], ['Drama'], ['Mystery'], ['Thriller'], ['Crime'], ['Drama'], ['Thriller'], ['Biography'], ['Crime'], ['Drama'], ['Action'], ['Adventure'], ['Fantasy'], ['Adventure'], ['Drama'], ['Sci-Fi'], ['Action'], ['Adventure'], ['Comedy'], ['Crime'], ['Drama'], ['Thriller'], ['Comedy'], ['Action'], ['Adventure'], ['Drama'], ['Drama'], ['Mystery'], ['Sci-Fi'], ['Action'], ['Horror'], ['Thriller'], ['Biography'], ['Drama'], ['History'], ['Action'], ['Fantasy'], ['War'], ['Adventure'], ['Drama'], ['Fantasy'], ['Comedy'], ['Horror'], ['Thriller'], ['Drama'], ['Horror'], ['Mystery'], ['Animation'], ['Adventure'], ['Comedy'], ['Adventure'], ['Drama'], ['Family'], ['Adventure'], ['Mystery'], ['Sci-Fi'], ['Adventure'], ['Comedy'], ['Romance'], ['Action'], ['Thriller'], ['Adventure'], ['Drama'], ['Family'], ['Action'], ['Adventure'], ['Sci-Fi'], ['Adventure'], ['Crime'], ['Mystery'], ['Comedy'], ['Family'], ['Musical'], ['Adventure'], ['Drama'], ['Thriller'], ['Drama'], ['Adventure'], ['Comedy'], ['Drama'], ['Drama'], ['Horror'], ['Thriller'], ['Drama'], ['Music'], ['Action'], ['Crime'], ['Thriller'], ['Crime'], ['Drama'], ['Thriller'], ['Crime'], ['Drama'], ['Thriller'], ['Drama'], ['Romance'], ['Mystery'], ['Thriller'], ['Action'], ['Adventure'], ['Sci-Fi'], ['Comedy'], ['Family'], ['Biography'], ['Comedy'], ['Drama'], ['Drama'], ['Drama'], ['Western'], ['Drama'], ['Mystery'], ['Romance'], ['Comedy'], ['Drama'], ['Action'], ['Drama'], ['Mystery'], ['Comedy'], ['Action'], ['Adventure'], ['Crime'], ['Adventure'], ['Family'], ['Fantasy'], ['Adventure'], ['Sci-Fi'], ['Thriller'], ['Drama'], ['Action'], ['Crime'], ['Drama'], ['Action'], ['Horror'], ['Sci-Fi'], ['Action'], ['Adventure'], ['Sci-Fi'], ['Comedy'], ['Drama'], ['Romance'], ['Action'], ['Comedy'], ['Fantasy'], ['Action'], ['Comedy'], ['Mystery'], ['Action'], ['Comedy'], ['Crime'], ['Action'], ['Adventure'], ['Sci-Fi'], ['Action'], ['Adventure'], ['Crime'], ['Action'], ['Adventure'], ['Thriller'], ['Drama'], ['Fantasy'], ['Romance'], ['Action'], ['Adventure'], ['Comedy'], ['Biography'], ['Drama'], ['History'], ['Action'], ['Drama'], ['History'], ['Action'], ['Adventure'], ['Thriller'], ['Crime'], ['Drama'], ['Thriller'], ['Animation'], ['Adventure'], ['Family'], ['Drama'], ['Romance'], ['Sci-Fi'], ['Animation'], ['Adventure'], ['Comedy'], ['Action'], ['Adventure'], ['Family'], ['Action'], ['Adventure'], ['Drama'], ['Action'], ['Comedy'], ['Horror'], ['Mystery'], ['Thriller'], ['Action'], ['Adventure'], ['Comedy'], ['Comedy'], ['Romance'], ['Horror'], ['Mystery'], ['Drama'], ['Family'], ['Fantasy'], ['Drama'], ['Thriller'], ['Drama'], ['War'], ['Drama'], ['Fantasy'], ['Horror'], ['Crime'], ['Drama'], ['Comedy'], ['Drama'], ['Romance'], ['Drama'], ['Romance'], ['Crime'], ['Drama'], ['History'], ['Horror'], ['Sci-Fi'], ['Thriller'], ['Action'], ['Drama'], ['Sport'], ['Action'], ['Adventure'], ['Sci-Fi'], ['Adventure'], ['Biography'], ['Drama'], ['Biography'], ['Drama'], ['Thriller'], ['Action'], ['Comedy'], ['Crime'], ['Action'], ['Adventure'], ['Sci-Fi'], ['Drama'], ['Fantasy'], ['Horror'], ['Biography'], ['Drama'], ['Thriller'], ['Action'], ['Adventure'], ['Sci-Fi'], ['Action'], ['Adventure'], ['Mystery'], ['Action'], ['Adventure'], ['Sci-Fi'], ['Drama'], ['Horror'], ['Comedy'], ['Drama'], ['Romance'], ['Comedy'], ['Romance'], ['Action'], ['Adventure'], ['Drama'], ['Drama'], ['Action'], ['Adventure'], ['Sci-Fi'], ['Action'], ['Adventure'], ['Fantasy'], ['Action'], ['Adventure'], ['Fantasy'], ['Action'], ['Adventure'], ['Sci-Fi'], ['Action'], ['Adventure'], ['Comedy'], ['Action'], ['Comedy'], ['Action'], ['Adventure'], ['Sci-Fi'], ['Animation'], ['Adventure'], ['Comedy'], ['Horror'], ['Mystery'], ['Crime'], ['Drama'], ['Mystery'], ['Comedy'], ['Crime'], ['Drama'], ['Comedy'], ['Drama'], ['Romance'], ['Action'], ['Adventure'], ['Sci-Fi'], ['Action'], ['Adventure'], ['Family'], ['Drama'], ['Fantasy'], ['War'], ['Crime'], ['Drama'], ['Thriller'], ['Action'], ['Adventure'], ['Drama'], ['Action'], ['Adventure'], ['Thriller'], ['Action'], ['Adventure'], ['Drama'], ['Drama'], ['Romance'], ['Biography'], ['Drama'], ['History'], ['Drama'], ['Horror'], ['Thriller'], ['Adventure'], ['Comedy'], ['Drama'], ['Action'], ['Adventure'], ['Romance'], ['Action'], ['Drama'], ['War'], ['Animation'], ['Adventure'], ['Comedy'], ['Animation'], ['Adventure'], ['Comedy'], ['Action'], ['Adventure'], ['Sci-Fi'], ['Adventure'], ['Family'], ['Fantasy'], ['Drama'], ['Musical'], ['Romance'], ['Drama'], ['Sci-Fi'], ['Thriller'], ['Comedy'], ['Drama'], ['Action'], ['Comedy'], ['Crime'], ['Biography'], ['Comedy'], ['Drama'], ['Comedy'], ['Drama'], ['Romance'], ['Drama'], ['Thriller'], ['Biography'], ['Drama'], ['History'], ['Action'], ['Adventure'], ['Sci-Fi'], ['Horror'], ['Mystery'], ['Thriller'], ['Comedy'], ['Action'], ['Adventure'], ['Sci-Fi'], ['Action'], ['Drama'], ['Sci-Fi'], ['Horror'], ['Drama'], ['Thriller'], ['Comedy'], ['Drama'], ['Romance'], ['Drama'], ['Thriller'], ['Comedy'], ['Drama'], ['Drama'], ['Action'], ['Adventure'], ['Comedy'], ['Drama'], ['Horror'], ['Thriller'], ['Comedy'], ['Drama'], ['Sci-Fi'], ['Action'], ['Adventure'], ['Sci-Fi'], ['Action'], ['Adventure'], ['Thriller'], ['Adventure'], ['Fantasy'], ['Action'], ['Comedy'], ['Crime'], ['Comedy'], ['Drama'], ['Music'], ['Action'], ['Adventure'], ['Mystery'], ['Action'], ['Comedy'], ['Crime'], ['Crime'], ['Drama'], ['History'], ['Comedy'], ['Action'], ['Adventure'], ['Sci-Fi'], ['Crime'], ['Mystery'], ['Thriller'], ['Action'], ['Adventure'], ['Crime'], ['Biography'], ['Drama'], ['Romance'], ['Action'], ['Adventure'], ['Action'], ['Fantasy'], ['Action'], ['Comedy'], ['Action'], ['Adventure'], ['Sci-Fi'], ['Action'], ['Comedy'], ['Crime'], ['Action'], ['Drama'], ['Horror'], ['Comedy'], ['Music'], ['Romance'], ['Comedy'], ['Action'], ['Adventure'], ['Fantasy'], ['Drama'], ['Romance'], ['Animation'], ['Adventure'], ['Comedy'], ['Comedy'], ['Drama'], ['Biography'], ['Crime'], ['Drama'], ['Drama'], ['History'], ['Action'], ['Crime'], ['Thriller'], ['Action'], ['Biography'], ['Drama'], ['Horror'], ['Comedy'], ['Romance'], ['Comedy'], ['Romance'], ['Comedy'], ['Crime'], ['Drama'], ['Adventure'], ['Family'], ['Fantasy'], ['Action'], ['Crime'], ['Thriller'], ['Comedy'], ['Romance'], ['Biography'], ['Drama'], ['Sport'], ['Drama'], ['Romance'], ['Drama'], ['Horror'], ['Adventure'], ['Fantasy'], ['Adventure'], ['Family'], ['Fantasy'], ['Action'], ['Drama'], ['Sci-Fi'], ['Action'], ['Adventure'], ['Sci-Fi'], ['Comedy'], ['Horror'], ['Thriller'], ['Action'], ['Crime'], ['Thriller'], ['Crime'], ['Drama'], ['Music'], ['Drama'], ['Action'], ['Crime'], ['Thriller'], ['Action'], ['Sci-Fi'], ['Thriller'], ['Biography'], ['Drama'], ['Action'], ['Adventure'], ['Fantasy'], ['Drama'], ['Horror'], ['Sci-Fi'], ['Biography'], ['Comedy'], ['Drama'], ['Crime'], ['Horror'], ['Thriller'], ['Crime'], ['Drama'], ['Mystery'], ['Animation'], ['Adventure'], ['Comedy'], ['Action'], ['Biography'], ['Drama'], ['Biography'], ['Drama'], ['Biography'], ['Drama'], ['History'], ['Action'], ['Biography'], ['Drama'], ['Comedy'], ['Drama'], ['Romance'], ['Drama'], ['Romance'], ['Comedy'], ['Romance'], ['Action'], ['Crime'], ['Thriller'], ['Action'], ['Crime'], ['Drama'], ['Action'], ['Drama'], ['Thriller'], ['Adventure'], ['Family'], ['Fantasy'], ['Action'], ['Adventure'], ['Action'], ['Adventure'], ['Romance'], ['Adventure'], ['Family'], ['Fantasy'], ['Crime'], ['Drama'], ['Comedy'], ['Horror'], ['Comedy'], ['Fantasy'], ['Romance'], ['Drama'], ['Comedy'], ['Drama'], ['Comedy'], ['Drama'], ['Romance'], ['Adventure'], ['Sci-Fi'], ['Thriller'], ['Action'], ['Adventure'], ['Fantasy'], ['Biography'], ['Drama'], ['Romance'], ['Comedy'], ['Fantasy'], ['Comedy'], ['Drama'], ['Fantasy'], ['Comedy'], ['Horror'], ['Thriller'], ['Action'], ['Adventure'], ['Sci-Fi'], ['Adventure'], ['Comedy'], ['Horror'], ['Comedy'], ['Mystery'], ['Drama'], ['Adventure'], ['Drama'], ['Fantasy'], ['Action'], ['Adventure'], ['Action'], ['Adventure'], ['Drama'], ['Action'], ['Drama'], ['Sci-Fi'], ['Action'], ['Mystery'], ['Sci-Fi'], ['Action'], ['Crime'], ['Drama'], ['Action'], ['Crime'], ['Fantasy'], ['Biography'], ['Comedy'], ['Drama'], ['Action'], ['Crime'], ['Thriller'], ['Biography'], ['Crime'], ['Drama'], ['Drama'], ['Sport'], ['Adventure'], ['Comedy'], ['Drama'], ['Action'], ['Adventure'], ['Thriller'], ['Comedy'], ['Fantasy'], ['Horror'], ['Drama'], ['Sport'], ['Drama'], ['History'], ['Thriller'], ['Animation'], ['Action'], ['Adventure'], ['Action'], ['Adventure'], ['Drama'], ['Action'], ['Comedy'], ['Family'], ['Action'], ['Adventure'], ['Drama'], ['Action'], ['Adventure'], ['Sci-Fi'], ['Action'], ['Adventure'], ['Sci-Fi'], ['Action'], ['Comedy'], ['Action'], ['Crime'], ['Drama'], ['Biography'], ['Drama'], ['Comedy'], ['Drama'], ['Fantasy'], ['Romance'], ['Action'], ['Adventure'], ['Sci-Fi'], ['Comedy'], ['Comedy'], ['Drama'], ['Animation'], ['Action'], ['Adventure'], ['Animation'], ['Adventure'], ['Comedy'], ['Drama'], ['Romance'], ['Drama'], ['Mystery'], ['Thriller'], ['Drama'], ['History'], ['Thriller'], ['Animation'], ['Adventure'], ['Comedy'], ['Action'], ['Adventure'], ['Sci-Fi'], ['Adventure'], ['Comedy'], ['Action'], ['Thriller'], ['Comedy'], ['Music'], ['Animation'], ['Adventure'], ['Comedy'], ['Action'], ['Adventure'], ['Crime'], ['Comedy'], ['Drama'], ['Horror'], ['Adventure'], ['Family'], ['Fantasy'], ['Drama'], ['Action'], ['Drama'], ['Thriller'], ['Drama'], ['Action'], ['Horror'], ['Romance'], ['Action'], ['Drama'], ['Fantasy'], ['Action'], ['Crime'], ['Drama'], ['Drama'], ['Fantasy'], ['Romance'], ['Action'], ['Crime'], ['Thriller'], ['Action'], ['Mystery'], ['Thriller'], ['Comedy'], ['Drama'], ['Comedy'], ['Action'], ['Adventure'], ['Horror'], ['Action'], ['Adventure'], ['Thriller'], ['Drama'], ['Romance'], ['Drama'], ['Thriller'], ['Action'], ['Comedy'], ['Crime'], ['Adventure'], ['Family'], ['Fantasy'], ['Drama'], ['Romance'], ['Animation'], ['Family'], ['Fantasy'], ['Drama'], ['Romance'], ['Action'], ['Sci-Fi'], ['Adventure'], ['Comedy'], ['Drama'], ['Animation'], ['Action'], ['Adventure'], ['Drama'], ['Horror'], ['Action'], ['Adventure'], ['Sci-Fi'], ['Comedy'], ['Drama'], ['Action'], ['Horror'], ['Mystery'], ['Action'], ['Thriller'], ['Action'], ['Adventure'], ['Sci-Fi'], ['Drama'], ['Comedy'], ['Drama'], ['Romance'], ['Comedy'], ['Crime'], ['Comedy'], ['Romance'], ['Drama'], ['Romance'], ['Crime'], ['Drama'], ['Thriller'], ['Horror'], ['Mystery'], ['Thriller'], ['Biography'], ['Drama'], ['Adventure'], ['Comedy'], ['Family'], ['Action'], ['Adventure'], ['Crime'], ['Action'], ['Crime'], ['Mystery'], ['Mystery'], ['Thriller'], ['Action'], ['Sci-Fi'], ['Thriller'], ['Action'], ['Comedy'], ['Crime'], ['Biography'], ['Crime'], ['Drama'], ['Biography'], ['Drama'], ['History'], ['Action'], ['Adventure'], ['Sci-Fi'], ['Adventure'], ['Family'], ['Fantasy'], ['Biography'], ['Drama'], ['History'], ['Biography'], ['Comedy'], ['Drama'], ['Drama'], ['Thriller'], ['Comedy'], ['Drama'], ['Romance'], ['Drama'], ['Romance'], ['Sci-Fi'], ['Action'], ['Crime'], ['Drama'], ['Adventure'], ['Comedy'], ['Drama'], ['Comedy'], ['Drama'], ['Family'], ['Drama'], ['Romance'], ['Thriller'], ['Comedy'], ['Crime'], ['Drama'], ['Animation'], ['Comedy'], ['Family'], ['Drama'], ['Horror'], ['Sci-Fi'], ['Action'], ['Adventure'], ['Drama'], ['Action'], ['Horror'], ['Sci-Fi'], ['Action'], ['Crime'], ['Sport'], ['Drama'], ['Horror'], ['Sci-Fi'], ['Drama'], ['Horror'], ['Sci-Fi'], ['Action'], ['Adventure'], ['Comedy'], ['Mystery'], ['Sci-Fi'], ['Thriller'], ['Crime'], ['Drama'], ['Thriller'], ['Animation'], ['Adventure'], ['Comedy'], ['Action'], ['Sci-Fi'], ['Thriller'], ['Drama'], ['Romance'], ['Comedy'], ['Drama'], ['Music'], ['Crime'], ['Drama'], ['Thriller'], ['Comedy'], ['Drama'], ['Romance'], ['Comedy'], ['Romance'], ['Drama'], ['Sci-Fi'], ['Thriller'], ['Drama'], ['War'], ['Action'], ['Crime'], ['Drama'], ['Sci-Fi'], ['Thriller'], ['Adventure'], ['Drama'], ['Horror'], ['Comedy'], ['Drama'], ['Romance'], ['Action'], ['Adventure'], ['Drama'], ['Action'], ['Crime'], ['Drama'], ['Adventure'], ['Fantasy'], ['Drama'], ['Romance'], ['Biography'], ['History'], ['Thriller'], ['Crime'], ['Drama'], ['Thriller'], ['Action'], ['Drama'], ['History'], ['Crime'], ['Drama'], ['Thriller'], ['Action'], ['Biography'], ['Drama'], ['Adventure'], ['Horror'], ['Action'], ['Adventure'], ['Sci-Fi'], ['Action'], ['Adventure'], ['Mystery'], ['Comedy'], ['Drama'], ['Romance'], ['Horror'], ['Thriller'], ['Action'], ['Sci-Fi'], ['Thriller'], ['Biography'], ['Drama'], ['Action'], ['Crime'], ['Drama'], ['Action'], ['Crime'], ['Mystery'], ['Action'], ['Adventure'], ['Comedy'], ['Mystery'], ['Thriller'], ['Mystery'], ['Sci-Fi'], ['Thriller'], ['Drama'], ['Mystery'], ['Sci-Fi'], ['Comedy'], ['Drama'], ['Adventure'], ['Family'], ['Fantasy'], ['Biography'], ['Drama'], ['Sport'], ['Comedy'], ['Drama'], ['Romance'], ['Biography'], ['Drama'], ['Romance'], ['Action'], ['Adventure'], ['Sci-Fi'], ['Mystery'], ['Thriller'], ['Mystery'], ['Thriller'], ['Action'], ['Drama'], ['Fantasy'], ['Action'], ['Adventure'], ['Biography'], ['Adventure'], ['Comedy'], ['Sci-Fi'], ['Action'], ['Adventure'], ['Thriller'], ['Fantasy'], ['Horror'], ['Horror'], ['Mystery'], ['Animation'], ['Adventure'], ['Comedy'], ['Action'], ['Adventure'], ['Drama'], ['Adventure'], ['Family'], ['Fantasy'], ['Action'], ['Adventure'], ['Sci-Fi'], ['Comedy'], ['Drama'], ['Comedy'], ['Drama'], ['Crime'], ['Drama'], ['Thriller'], ['Comedy'], ['Romance'], ['Animation'], ['Comedy'], ['Family'], ['Comedy'], ['Drama'], ['Comedy'], ['Drama'], ['Biography'], ['Drama'], ['Sport'], ['Action'], ['Adventure'], ['Fantasy'], ['Action'], ['Drama'], ['History'], ['Action'], ['Adventure'], ['Sci-Fi'], ['Action'], ['Adventure'], ['Mystery'], ['Crime'], ['Drama'], ['Mystery'], ['Action'], ['Comedy'], ['Romance'], ['Comedy'], ['Drama'], ['Romance'], ['Biography'], ['Drama'], ['Sport'], ['Action'], ['Fantasy'], ['Thriller'], ['Biography'], ['Drama'], ['Sport'], ['Action'], ['Drama'], ['Fantasy'], ['Adventure'], ['Sci-Fi'], ['Thriller'], ['Animation'], ['Adventure'], ['Comedy'], ['Drama'], ['Mystery'], ['Thriller'], ['Drama'], ['Romance'], ['Crime'], ['Drama'], ['Mystery'], ['Comedy'], ['Romance'], ['Sport'], ['Comedy'], ['Family'], ['Drama'], ['Horror'], ['Mystery'], ['Action'], ['Drama'], ['Sport'], ['Action'], ['Adventure'], ['Comedy'], ['Drama'], ['Mystery'], ['Sci-Fi'], ['Animation'], ['Action'], ['Comedy'], ['Action'], ['Crime'], ['Drama'], ['Action'], ['Crime'], ['Drama'], ['Animation'], ['Action'], ['Adventure'], ['Crime'], ['Drama'], ['Comedy'], ['Crime'], ['Drama'], ['Action'], ['Adventure'], ['Fantasy'], ['Drama'], ['Fantasy'], ['Romance'], ['Comedy'], ['Drama'], ['Drama'], ['Fantasy'], ['Thriller'], ['Biography'], ['Crime'], ['Drama'], ['Comedy'], ['Drama'], ['Romance'], ['Action'], ['Crime'], ['Drama'], ['Sci-Fi'], ['Action'], ['Comedy'], ['Romance'], ['Adventure'], ['Comedy'], ['Drama'], ['Comedy'], ['Crime'], ['Drama'], ['Action'], ['Fantasy'], ['Horror'], ['Drama'], ['Horror'], ['Horror'], ['Action'], ['Thriller'], ['Action'], ['Adventure'], ['Mystery'], ['Action'], ['Adventure'], ['Fantasy'], ['Adventure'], ['Comedy'], ['Family'], ['Comedy'], ['Drama'], ['Romance'], ['Comedy'], ['Comedy'], ['Drama'], ['Horror'], ['Comedy'], ['Romance'], ['Mystery'], ['Romance'], ['Sci-Fi'], ['Crime'], ['Drama'], ['Drama'], ['Horror'], ['Mystery'], ['Comedy'], ['Biography'], ['Drama'], ['Comedy'], ['Drama'], ['Thriller'], ['Drama'], ['History'], ['War'], ['Comedy'], ['Drama'], ['Action'], ['Comedy'], ['Fantasy'], ['Drama'], ['Horror'], ['Musical'], ['Horror'], ['Mystery'], ['Thriller'], ['Comedy'], ['Music'], ['Biography'], ['Crime'], ['Drama'], ['Drama'], ['Action'], ['Adventure'], ['Comedy'], ['Crime'], ['Drama'], ['Mystery'], ['Drama'], ['Action'], ['Comedy'], ['Crime'], ['Comedy'], ['Drama'], ['Romance'], ['Crime'], ['Drama'], ['Mystery'], ['Action'], ['Comedy'], ['Crime'], ['Drama'], ['Drama'], ['Romance'], ['Crime'], ['Drama'], ['Mystery'], ['Adventure'], ['Comedy'], ['Romance'], ['Comedy'], ['Crime'], ['Drama'], ['Adventure'], ['Drama'], ['Thriller'], ['Crime'], ['Drama'], ['Thriller'], ['Drama'], ['History'], ['Thriller'], ['Action'], ['Adventure'], ['Sci-Fi'], ['Horror'], ['Action'], ['Crime'], ['Mystery'], ['Comedy'], ['Romance'], ['Comedy'], ['Action'], ['Drama'], ['Thriller'], ['Action'], ['Adventure'], ['Sci-Fi'], ['Drama'], ['Mystery'], ['Thriller'], ['Comedy'], ['Drama'], ['Romance'], ['Action'], ['Fantasy'], ['Horror'], ['Drama'], ['Romance'], ['Biography'], ['Drama'], ['Biography'], ['Drama'], ['Action'], ['Adventure'], ['Sci-Fi'], ['Animation'], ['Adventure'], ['Comedy'], ['Drama'], ['Mystery'], ['Thriller'], ['Action'], ['Horror'], ['Sci-Fi'], ['Drama'], ['Romance'], ['Action'], ['Adventure'], ['Drama'], ['Adventure'], ['Drama'], ['Fantasy'], ['Drama'], ['Romance'], ['Sci-Fi'], ['Action'], ['Adventure'], ['Thriller'], ['Comedy'], ['Fantasy'], ['Action'], ['Comedy'], ['Crime'], ['Adventure'], ['Drama'

In [98]:
unique_list=[]
for x in new_list:
    if x not in unique_list:
        unique_list.append(x)
print(unique_list)

[['Action'], ['Adventure'], ['Sci-Fi'], ['Mystery'], ['Horror'], ['Thriller'], ['Animation'], ['Comedy'], ['Family'], ['Fantasy'], ['Drama'], ['Music'], ['Biography'], ['Romance'], ['History'], ['Western'], ['Crime'], ['War'], ['Musical'], ['Sport']]

In [101]:
len(unique_list)

20